# Generated by Django 4.2.9 on 2024-07-09 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=255)),
                ('change_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_description', models.TextField()),
                ('pricing_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='DayPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_multiplier_factor', models.JSONField()),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pricing_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_pricing', to='pricing.pricingconfig')),
            ],
            options={
                'unique_together': {('pricing_config', 'day_of_week')},
            },
        ),
    ]
