# Generated by Django 4.2.9 on 2024-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daypricingconfig',
            old_name='distance_additional_price',
            new_name='additional_price_per_km',
        ),
        migrations.RenameField(
            model_name='daypricingconfig',
            old_name='distance_base_price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='daypricingconfig',
            name='base_distance',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
    ]
