# Generated by Django 4.2.9 on 2024-07-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_rename_distance_additional_price_daypricingconfig_additional_price_per_km_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daypricingconfig',
            old_name='base_distance',
            new_name='base_distance_upto_km',
        ),
    ]
