# Generated by Django 3.2.5 on 2024-07-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sgst',
        ),
    ]
